name: Streamkeys
markdown: redcarpet
highlighter: pygments
url: http://localhost:4000
baseTitle: Streamkeys - Global Music Player Hotkeys for Chrome -
destination: ./build/_site
source: ./code
assets:
  sources:
    - _assets/javascripts
    - _assets/images
    - _assets/stylesheets
navigation:
  faq: faq.html
  help: guide.html
  sitelist: sites.html
  home: index.html
  contact: contact.html
  changelog: changelog.html
  donate: donate.html
sitelist:
  - name: 8tracks
    image: icons/8tracks.png
    url: www.8tracks.com
  - name: Bandcamp
    image: icons/bandcamp.png
    url: www.bandcamp.com
  - name: Deezer
    image: icons/deezer.png
    url: www.deezer.com
  - name: Di.fm
    image: icons/difm.png
    url: www.di.fm
  - name: Earbits
    image: icons/earbits.png
    url: www.earbits.com
  - name: Google Play
    image: icons/gplay.png
    url: play.google.com
  - name: Grooveshark
    image: icons/grooveshark.png
    url: www.grooveshark.com
  - name: TheHypeMachine
    image: icons/hypemachine.png
    url: www.hypem.com
  - name: iHeartRadio
    image: icons/iheart.png
    url: www.iheart.com
  - name: Jango
    image: icons/jango.png
    url: www.jango.com
  - name: MixCloud
    image: icons/mixcloud.png
    url: www.mixcloud.com
  - name: Pandora
    image: icons/pandora.png
    url: www.pandora.com
  - name: RadioParadise
    image: icons/radioparadise.png
    url: www.radioparadise.com
  - name: Rdio
    image: icons/rdio.png
    url: www.rdio.com
  - name: Spotify
    image: icons/spotify.png
    url: www.spotify.com
  - name: Songstr
    image: icons/songstr.png
    url: www.songstr.com
  - name: Songza
    image: icons/songza.png
    url: www.songza.com
  - name: Stitcher
    image: icons/stitcher.png
    url: www.stitcher.com
  - name: Soundcloud
    image: icons/soundcloud.png
    url: www.soundcloud.com
  - name: Slacker
    image: icons/slacker.png
    url: www.slacker.com
  - name: YouTube
    image: icons/yt.png
    url: www.youtube.com
  - name: VK
    image: icons/vk.png
    url: www.vk.com
  - name: Plex
    image: icons/plex.png
    url: www.plex.tv
  - name: TheSixtyOne
    image: icons/thesixtyone.png
    url: www.thesixtyone.com
  - name: 7digital
    image: icons/7digital.png
    url: www.7digital.com
  - name: Amazon Music
    image: icons/amazon.png
    url: www.amazon.com
  - name: NPR Infinite Player
    image: icons/npr.png
    url: one.npr.org
  - name: AmbientSleepingPill
    image: icons/ambientsleepingpill.png
    url: www.ambientsleepingpill.com
  - name: Cubic.fm
    image: icons/cubicfm.png
    url: www.cubic.fm
  - name: Disco.io
    image: icons/discoio.png
    url: www.disco.io
  - name: OPlayer 
    url: www.oplayer.org
  - name: PocketCasts
    image: icons/pocketcasts.png
    url: www.pocketcasts.com
  - name: Rainwave.cc
    image: icons/rainwave.png
    url: www.rainwave.cc
  - name: TuneIn
    image: icons/tunein.png
    url: www.tunein.com
  - name: Yandex
    image: icons/yandex.png
    url: www.yandex.ru
  - name: YouAreListeningTo
    url: www.youarelistening.to
  - name: Beats Music
    image: icons/beats.png
    url: www.beatsmusic.com
  - name: Radio Swiss Jazz
    image: icons/radioswissjazz.png
    url: www.radioswissjazz.ch
  - name: Bop.fm
    image: icons/bopfm.jpg
    url: www.bop.fm
  - name: Edge Player
    image: icons/edgeplayer.png
    url: player.edge.ca
  - name: Gaana
    image: icons/gaana.png
    url: www.gaana.com
  - name: Laracasts
    image: icons/laracasts.png
    url: www.laracasts.com
  - name: Last.fm
    image: icons/lastfm.png
    url: www.last.fm
  - name: Myspace
    image: icons/myspace.png
    url: www.myspace.com
  - name: Pleer
    image: icons/pleer.png
    url: www.pleer.com
  - name: Saavn
    image: icons/saavn.png
    url: www.saavn.com
  - name: Seesu
    image: icons/seesu.png
    url: www.seesu.me
  - name: Sony Music Unlimited
    image: icons/sonymusicunlimited.png
    url: music.sonyentertainmentnetwork.com
  - name: Player.fm
    image: icons/playerfm.png
    url: www.player.fm
  - name: Kollekt.fm
    image: icons/kollektfm.png
    url: www.kollekt.fm
  - name: My Cloud Player
    image: icons/mycloudplayer.png
    url: www.mycloudplayers.com
  - name: Spreaker
    image: icons/spreaker.png
    url: www.spreaker.com
  - name: PalcoMP3
    image: icons/palcomp3.png
    url: www.palcomp3.com
  - name: ShortOrange
    image: icons/shortorange.png
    url: www.shortorange.com
  - name: Reverb Nation
    image: icons/reverbnation.png
    url: www.reverbnation.com
  - name: Shuffler.fm
    image: icons/shuffler.png
    url: www.shuffler.fm
  - name: Ivoox
    image: icons/ivoox.png
    url: www.ivoox.com
  - name: Tidal
    image: icons/tidal.png
    url: www.tidal.com
  - name: Sound.is
    url: www.sound.is
  - name: Soundsgood.co
    image: icons/soundsgood.png
    url: www.soundsgood.co
  - name: ASoftMurmur
    url: www.asoftmurmur.com
  - name: The Drop Club
    image: icons/thedropclub.png
    url: www.thedrop.club
  - name: Audiosplitter
    image: icons/audiosplitter.png
    url: www.audiosplitter.fm
  - name: Zonga
    image: icons/zonga.png
    url: www.zonga.ro
  - name: Blitzr
    url: www.blitzr.com
  - name: Emby
    url: www.emby.media
  - name: Twitch
    url: www.twitch.tv
  - name: Netflix
    url: www.netflix.com
  - name: Music Player for Reddit
    url: reddit.musicplayer.io
changelog:
  - version: v1.4.9
    content: >
      <p>Added support for new Spotify player UI (thanks <a href="https://github.com/matteosecli" target="_blank">@matteosecli</a> & <a href="https://github.com/henriquetorres" target="_blank">@henriquetorres</a>), RedditMusicPlayer</p>
      <p>Fixed bugs with Kollekt.fm, ShortOrange, Souncloud, YouTube, NPR.</p>
  - version: v1.4.8
    content: >
      <p>Added support for Twitch.tv, Netflix and new Cubic.fm player</p>
      <p>Fixed bugs with NPR player</p>
  - version: v1.4.6
    content: >
      <p>Added support for new YouTube player (<a href="http://www.youtube.com/testtube" target="_blank">youtube.com/testtube</a>)</p>
      <p>Fixed problems with Google Music, Pockcasts, 8tracks and Soundcloud</p>
      <p>Added support for Blitzr, Audiosplitter, Zonga (thanks <a href="https://github.com/dsilvius" target="_blank">@dsilvius</a>), Emby (thanks <a href="https://github.com/SkylerLipthay" target="_blank">@SkylerLipthay</a>)</p>
  - version: v1.4.5
    content: >
      <p>Added support for Shuffler.fm, Ivoox, Tidal, Sound.is, Soundsgood.co, ASoftMurmur, The Drop Club (thanks <a href="https://github.com/brandonjyuhas" target="_blank">@brandonjyuhas</a>!)</p>
      <p>Fixed problems with Yandex (thanks <a href="https://github.com/Guria" target="_blank">@Guria</a>)</p>
  - version: v1.4.4
    content: >
      <p>Added support for Player.fm, Kollekt.fm, My Cloud Player, Spreaker, PalcoMP3, ShortOrange and Reverb Nation</p>
      <p>Fixed problems with new Di.fm and Last.fm players</p>
      <p>Big improvements to the player popup! Added player controls for each tab, song/artist name tracking and individual tab settings. You can now quickly toggle support for specific tabs from the extension popup</p>
  - version: v1.4.3
    content: >
      <p>Added support for Xbox Music, Hypster, Laracasts, Gaana and Saavn(thanks <a href="https://github.com/lalwanivikas" target="_blank">@lalwanivikas</a>!)</p>
      <p>Fixed bugs with Slacker and Cubic.fm</p>
      <p>Added like/dislike feature for: 8tracks, Cubic, Deezer, Di.fm, Earbits, Google Music, Grooveshark, Hypem, Jango, Mixcloud, OPlayer, Pandora, Spotify, Yandex, Youtube. Set the hotkeys on the Chrome extensions settings page or use the popup player. Thanks to <a href="https://github.com/y-gagar1n" target="_blank">@y-gagar1n</a> for the help! Get in touch with me if there is a site missing.</p>
      <p>New site! Thanks to <a href="https://github.com/lalwanivikas" target="_blank">@lalwanivikas</a> for the design.</p>
  - version: v1.4.2
    content: >
      <p>Fixed bugs with Amazon (thanks <a href="https://github.com/Tito1337" target="_blank">@Tito1337</a>!) and Bop.fm</p>
      <p>Added support for Beats Music (thanks <a href="https://github.com/joero4" target="_blank">@joero4</a>!) and RadioSwissJazz.ch</p>
  - version: v1.4.1
    content: >
      <p>Added an icon and control window to enable/disable specific sites and tabs quickly</p>
      <p>Fixed bugs with Youtube playlists, Soundcloud, Pocketcasts and lastfm.ru</p>
      <p>Added support for rainwave.cc, cubic.fm, disco.io, oplayer.org</p>
  - version: v1.4.0
    content: >
      <p>Added support for Yandex Music, PocketCasts (thanks <a href="https://github.com/Rorgy" target="_blank">@Rorgy</a>!), Ambient Sleeping Pill (thanks <a href="https://github.com/inverse" target="_blank">@inverse</a>!)</p>
      <p>Fix bugs with Jango, VK, Deezer and iHeartRadio</p>
  - version: v1.3.6
    content: >
      <p>Added support for Bop.fm, Last.fm, Sony Music Unlimited (thanks <a href="https://github.com/inverse" target="_blank">@inverse</a>!), Pleer (thanks <a href="https://github.com/ulex" target="_blank">@ulex</a>!), YouAreListening.to</p>
  - version: v1.3.5
    content: >
      <p>Fixed bugs with Jango</p>
      <p>Added support for YouTube (disabled by default, enable on options page!), Plex.tv, Amazon Cloud Player, NPR Infinite Player, 7digital</p>
  - version: v1.3.4
    content: >
      <p>Fixed bugs with Songza and Slacker Radio</p>
      <p>Added support for di.fm, player.edge.ca, RadioParadise, Songstr</p>
  - version: v1.3.3
    content: >
      <p>Fixed bug introduced in 1.3.2 that broke functionality. Big thanks to those users who submitted bug reports!</p>
  - version: v1.3.2
    content: >
      <p>Added an options page which lets you enable/disable sites. To get to the options page go to the extension tab in Chrome (thanks <a href="https://github.com/dreyks" target="_blank">@Dreyks</a>!)</p>
      <p>Added support for Seesu.me, iHeartRadio, Mixcloud</p>
      <p>Fixed bug where having different players open at same time causes issues</p>
  - version: v1.3.1
    content: >
      <p>Added support for VK, Stitcher</p>
      <p>Fixed Google Music clicking inputs twice</p>
  - version: v1.3.0
    content: >
      <p>Added support for global hotkeys across entire system. <a href="guide.html#global">Read here for more info</a></p>
      <p>Added support for: Earbits, Songza</p>
      <p>Fixed Google Music support (thanks <a href="https://github.com/findmory-livefyre" target="_blank">@findmory</a>!)</p>
  - version: v1.2.0
    content: >
      <p>Reworked the whole extension so that capturing works much better and from anywhere on the chrome window</p>
      <p>Added support for Google Music, Jango, Thesixtyone, Slacker</p>
      <p>Removed the options page</p>
  - version: v1.1.0
    content: >
      <p>Added support for 8tracks, Deezer, Pandora, Spotify, Soundcloud, Hypemachine and Myspace</p>
      <p>Media keys now default to enabled</p>
  - version: v1.0.5
    content: >
      <p>Added support for Rdio</p>
      <p>Fixed some problems with option page</p>
  - version: v1.0
    content: >
      <p>Chrome Webstore release</p>
  - version: v0.9.5
    content: >
      <p>Added hotkey support for Bandcamp</p>
  - version: v0.9
    content: >
      <p>Media key support added</p>
      <p>Added an option page which can be accessed via the chrome extension tab</p>
  - version: v0.8
    content: >
      <p>Initial release</p>
